language: groovy

install:
 - ./gradlew clean -PbintrayUserName= -PbintrayApiKey --info --gradle-user-home=$(pwd)/../gradleHome

script:
 - ./gradlew build gradleTest -PbintrayUserName= -PbintrayApiKey --info --gradle-user-home=$(pwd)/../gradleHome

jdk:
 - oraclejdk7
 - oraclejdk8
 - openjdk6

os:
 - linux

env: TERM=dumb
